Calendar
y-scope/yscope-log-viewer pull request #23
Opened 2023-05-08 06:05 UTC by LinZhihao-723

# Description
Add a new functionality in the menu bar called "Calendar" which allows users to select a timestamp (in UTC seconds). The viewer will then jump to the first event with the timestamp greater or equal to the selected one.
The UI looks like the following:

# Validation performed
1. Manually test the functionality.
2. Add unit tests for UTC timestamp converting.

2023-05-08 06:06 UTC, LinZhihao-723 commented
Here are two screenshots of the viewer:

1. Menu bar
<img width="230" alt="bece782480627bc9f040a9876e4bb11" src="https://user-images.githubusercontent.com/59785146/236746519-ee06bd78-3d48-4a91-9fcf-67955d8855c0.png">

2. Calendar opened
<img width="801" alt="9fee379d5dd0d1743a2119c376f1b22" src="https://user-images.githubusercontent.com/59785146/236746465-5e82ef23-671c-4dc0-8959-8a3d04b514b2.png">

2023-05-28 20:59 UTC, Bill-hbrhbr commented on src/Viewer/components/MenuBar/MenuBar.js
> +    };
These two functions seem a bit unnecessary

2023-05-28 21:14 UTC, LinZhihao-723 commented on src/Viewer/components/MenuBar/MenuBar.js
> +    };
True, I agree

2023-05-28 21:18 UTC, Bill-hbrhbr requested changes
Leaving the rest to our protagonist Kirk,

2023-05-28 21:18 UTC, Bill-hbrhbr commented on src/Viewer/services/ActionHandler.js
> +        this._logFile.state.logEventIdx = this._logFile.getLogEventIdxFromTimestamp(timestamp);
I think the newest private class variable syntax is using #. I'm not sure if the _ prefix here means something should be private.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

2023-05-28 21:18 UTC, Bill-hbrhbr commented on src/Viewer/services/ActionHandler.js
> +        if (!isNumeric(timestamp)) {
Don't wanna be that guy, but

`false === isNumeric(timestamp)`

2023-05-28 21:18 UTC, Bill-hbrhbr commented on src/Viewer/components/MenuBar/MenuBar.js
> +        new Date(Math.floor(Date.now() / 1000) * 1000)
Could make the millisecond truncation into a function.

2023-05-28 21:18 UTC, Bill-hbrhbr commented on src/Viewer/components/MenuBar/MenuBar.js
> +            setCalendarDateTime(newDate);
use the millisecond truncation function here as well for consistent calendarDateTime state behavior (although maybe you already pass in a date value with the millisecond part removed).

2024-11-13 12:45 UTC, kirkrodrigues commented
Since the UI has been rewritten, can we close this PR and open a feature request for this feature?

2024-11-13 17:44 UTC, junhaoliao commented
The feature is now tracked by #117 & #118 . Closing this since we will have to open separate PRs when the code is ready to be submitted.

2024-11-13 17:44 UTC, closed without merging